apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: experiment-api-rolebinding
  namespace: experiment-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: experiment-api-role
subjects:
- kind: ServiceAccount
  name: experiment-api
  namespace: experiment-backend
