apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: experiment-api-role
  namespace: experiment-backend
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
