apiVersion: v1
kind: Service
metadata:
  name: experiment-api-service
  namespace: experiment-backend
  labels:
    app: experiment-api
spec:
  type: LoadBalancer
  selector:
    app: experiment-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
